export function segmentText(text: string, locale: string): string[] {
    if (typeof Intl !== 'undefined' && 'Segmenter' in Intl) {
        const segmenter = new Intl.Segmenter(locale, { granularity: 'word' });
        const segments = segmenter.segment(text);
        return Array.from(segments).map(s => s.segment);
    }
    return simpleSegmentText(text);
}

export function simpleSegmentText(text: string) {
    // Wraps in a capturing group to retain delimiters in the split output.
    // Matches:
    // - \s+           : One or more whitespace characters
    // - \p{P}+        : One or more punctuation characters (requires 'u' flag)
    // - \u4E00-\u9FFF : CJK Unified Ideographs (Han) - individual characters
    // - \u3040-\u309F : Hiragana - individual characters
    // - \u30A0-\u30FF : Katakana - individual characters
    // - \uAC00-\uD7A3 : Hangul Syllables - individual characters
    const regex =
        /([\s]+|[\p{P}]+|[\u4E00-\u9FFF\u3040-\u309F\u30A0-\u30FF\uAC00-\uD7A3])/u;

    // Split the string and filter out any empty strings generated by consecutive delimiters
    return text.split(regex).filter(segment => segment.length > 0);
}
